language: go

go:
  - 1.7

sudo: required

services:
  - docker

script:
  - docker build -t rosytucker/codenight:latest .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push rosytucker/codenight:latest;
    fi